name: medai_mobile
description: MedAI Mobile App - One AI chat, every hospital.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.18.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.1.0

  # Networking & AI
  http: ^1.2.2

  # Media & Storage
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  flutter_secure_storage: ^9.2.2

  # Google Sign-In (optional)
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
